/**
 * @name PUBLIC_ENV
 * @description This is the public environment variables that are available to the client.
 * We use this to expose public environment variables to the client.
 */
export const PUBLIC_ENV = {
  REMIX_PUBLIC_SITE_URL: process.env.REMIX_PUBLIC_SITE_URL,
  REMIX_PUBLIC_PRODUCT_NAME: process.env.REMIX_PUBLIC_PRODUCT_NAME,
  REMIX_PUBLIC_SITE_TITLE: process.env.REMIX_PUBLIC_SITE_TITLE,
  REMIX_PUBLIC_SITE_DESCRIPTION: process.env.REMIX_PUBLIC_SITE_DESCRIPTION,
  REMIX_PUBLIC_DEFAULT_THEME_MODE: process.env.REMIX_PUBLIC_DEFAULT_THEME_MODE,
  REMIX_PUBLIC_THEME_COLOR: process.env.REMIX_PUBLIC_THEME_COLOR,
  REMIX_PUBLIC_THEME_COLOR_DARK: process.env.REMIX_PUBLIC_THEME_COLOR_DARK,
  REMIX_PUBLIC_AUTH_PASSWORD: process.env.REMIX_PUBLIC_AUTH_PASSWORD,
  REMIX_PUBLIC_AUTH_MAGIC_LINK: process.env.REMIX_PUBLIC_AUTH_MAGIC_LINK,
  REMIX_PUBLIC_CAPTCHA_SITE_KEY: process.env.REMIX_PUBLIC_CAPTCHA_SITE_KEY,
  REMIX_PUBLIC_BILLING_PROVIDER: process.env.REMIX_PUBLIC_BILLING_PROVIDER,
  REMIX_PUBLIC_ENABLE_THEME_TOGGLE:
    process.env.REMIX_PUBLIC_ENABLE_THEME_TOGGLE,
  REMIX_PUBLIC_ENABLE_PERSONAL_ACCOUNT_DELETION:
    process.env.REMIX_PUBLIC_ENABLE_PERSONAL_ACCOUNT_DELETION,
  REMIX_PUBLIC_ENABLE_PERSONAL_ACCOUNT_BILLING:
    process.env.REMIX_PUBLIC_ENABLE_PERSONAL_ACCOUNT_BILLING,
  REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_DELETION:
    process.env.REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_DELETION,
  REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_BILLING:
    process.env.REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_BILLING,
  REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS:
    process.env.REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS,
  REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_CREATION:
    process.env.REMIX_PUBLIC_ENABLE_TEAM_ACCOUNTS_CREATION,
  REMIX_PUBLIC_LANGUAGE_PRIORITY: process.env.REMIX_PUBLIC_LANGUAGE_PRIORITY,
  REMIX_PUBLIC_LOCALES_PATH: process.env.REMIX_PUBLIC_LOCALES_PATH,
  REMIX_PUBLIC_KEYSTATIC_CONTENT_PATH:
    process.env.REMIX_PUBLIC_KEYSTATIC_CONTENT_PATH,
  REMIX_PUBLIC_SUPABASE_URL: process.env.REMIX_PUBLIC_SUPABASE_URL,
  REMIX_PUBLIC_SUPABASE_ANON_KEY: process.env.REMIX_PUBLIC_SUPABASE_ANON_KEY,
    REMIX_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.REMIX_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  REMIX_PUBLIC_CMS_CLIENT: process.env.REMIX_PUBLIC_CMS_CLIENT,
};
